CREATE TABLE settings (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    company_name NVARCHAR(100) NOT NULL,
    invoice_note NVARCHAR(100) NOT NULL,
    invoice_print_name NVARCHAR(100) NOT NULL,
    invoice_print_type NVARCHAR(100) NOT NULL,
    line1 NVARCHAR(300) NULL,    
    line2 NVARCHAR(300) NULL,    
    line3 NVARCHAR(300) NULL 	 
);

CREATE TABLE users
(
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    name NVARCHAR(100) NOT NULL,
    user_name NVARCHAR(50) NOT NULL UNIQUE,
    password NVARCHAR(255) NOT NULL,
	rol NVARCHAR(50) NOT NULL,
    is_actived BIT NOT NULL DEFAULT 1,
	created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
);
